### ISSUE TITLE
Before building, you have to install libspdlog-dev

### ISSUE THREAD

**Issue by AnaRhisT94** [carlospzlz/ctello#2]
Hi,
because of spdlog requirement,
libspdlog-dev installation is required.

`sudo apt-get install libspdlog-dev`

**Comment by carlospzlz** [comment]
Hi,
`spdlog` is listed in the **Dependencies** section in the `README`, before **Build & Install**. Do you find that's not clear enough?

**Comment by AnaRhisT94** [comment]
Totally ok, just to let others know that this package has to be installed so spdlog's requirement is fullfilled.
