### ISSUE TITLE
libctello.so isn't added automatically to LD_LIBRARY_PATH ?

### ISSUE THREAD

**Issue by AnaRhisT94** [carlospzlz/ctello#4]
Error when trying to build it:
`error while loading shared libraries: libctello.so: cannot open shared object file: No such file or directory`

Do I need to add manually libctello.so to the library path? I thought the `sudo make install `command should take care of it.

**Comment by carlospzlz** [comment]
What are you building and how are you building it?

**Comment by AnaRhisT94** [comment]
I'm trying to build the simple program in the README,
Using this command:
`g++ -std=c++17 -I/usr/local/include -L/usr/local/lib flip_world.cpp -lctello -o flip-world
`

**Comment by AnaRhisT94** [comment]
**This is the solution:**
`g++ -std=c++17 -I/home/a/Desktop/projects/ctello/include/ -L/usr/local/lib -Wl,-R/usr/local/lib tello-hello.cpp -lctello -o tello-hello.o`.

The` -Wl,-R `part tells the resulting binary to also look for the library in `/usr/local/lib` at runtime before trying to use the one in `/usr/lib/.`

**Comment by carlospzlz** [comment]
When building, `-L/usr/local/lib` tells the linker to look for libraries in `/usr/local/lib`.

What you are describing looks more like a runtime problem; the library cannot be found when your program starts. You usually deal with this by appending the directory path to the `LD_LIBRARY_PATH` environment variable. This is highlighted in the `README`, in the **Quickstart** section, when running the `flip-world` example:

> Run your flip-world (you may need to add `/usr/local/lib` to your `LD_LIBRARY_PATH`)
